spring.application.name=tecterra-billing
spring.main.allow-bean-definition-overriding=true
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

mikrotik.url=http://192.168.1.1
mikrotik.user=tecterra_user
mikrotik.password=15121416